#server:
#  port: 9013
  
#zuul:
#  routes: 
#    demo:
#      path: /demo/employee
#      service-id: 9007
#      strip-prefix: false

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/